name: Build and push image

on:
  push:
    branches:
      - main


jobs:
  build_and_publush:
    runs-on: ubuntu-latest

    steps: 

    - name: Login to AWS ECR Public registry
      uses: docker/login-action@v1
      with:
        registry: public.ecr.aws
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        push: true
        file: .gitpod/Dockerfile
        tags: |
            public.ecr.aws/vlad-labs/gitpod-cloud-engineer-helper:latest
            public.ecr.aws/vlad-labs/gitpod-cloud-engineer-helper:${{ github.sha }}