name: Build and push image

on:
  push:
    branches:
      - main

jobs:
  build_and_publush:
    runs-on: ubuntu-latest

    steps: 
    - uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: gitpod-cloud-helper
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG . -f .gitpod/Dockerfile
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG latest
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG