name: Build and push image

on:
  push:
    branches:
      - main

env:
  AWS_ECR_PUB_REGISTRY: public.ecr.aws

jobs:
  build_and_publush:
    runs-on: ubuntu-latest

    steps: 

    - name: Login to AWS ECR Public
      uses: docker/login-action@v1
      with:
        registry: ${{ env.AWS_ECR_PUB_REGISTRY }}
        username: ${{ secrets.AWS_ACCESS_KEY_ID }}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY:  ${{ env.AWS_ECR_PUB_REGISTRY }}
        ECR_REPOSITORY: vlad-labs/gitpod-cloud-helper
        COMMIT_SHA: ${{ github.sha }}
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest . -f .gitpod/Dockerfile
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:$COMMIT_SHA
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest